# Generated by Django 5.0.4 on 2024-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("preparation_steps", models.TextField()),
                ("cooking_time", models.CharField(max_length=50)),
                ("serving_size", models.CharField(max_length=50)),
                ("dietary_information", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="recipe_images/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Dessert", "Dessert"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
