# Generated by Django 5.0.4 on 2024-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
