# Generated by Django 5.0.4 on 2024-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_recipe_review_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_time",
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooking_time_minutes",
            field=models.IntegerField(
                blank=True, help_text="Enter cooking time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
