# Generated by Django 5.0.4 on 2024-04-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_profile_followers_profile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(related_name="following", to="login.profile"),
        ),
    ]
