# Generated by Django 5.0.4 on 2024-04-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_remove_profile_following_alter_profile_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.TextField(blank=True, null=True),
        ),
    ]
