# Generated by Django 5.0.4 on 2024-04-23 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_remove_profile_followers_profile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
    ]
